pipeline {
  agent {
    label "master"
  }

  stages {
    stage("Test"){
      steps {
        echo "Projeto do frontend"
        sh "ls"
        
        dir("/backend"){
          echo "Diretório do Backend"
          sh "ls"
        }
        
        dir("/frontend"){
          echo "Diretório do Frontend"
          sh "ls"
        }
      }
    }
  }
}
